name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

     
      # - name: Type Check
      #   run: npx tsc --noEmit || echo "Type check skipped"

      - name: Build (if exists)
        run: npm run build || echo "No build step yet"
